#!/usr/bin/php
<?php
error_reporting(E_ALL & ~E_NOTICE);
/*
 ---- DESCRIPTION ----
 wordpress plugin for munin
  it's a simple plugin to monitor users, comments, pingbacks
  and your posts from your wordpress homepage.

  Simply put your path of wp-config.php in your munin-node 
  configuration and this plugin does the rest for you.
  Happy monitoring! :)

  This plugin was inspired by the existing wordpress plugin in bash/sh:
   https://github.com/munin-monitoring/contrib/blob/master/plugins/other/wordpress


 ---- CONFIGURATION ----
 You just need to provide the path to your
 wp-config.php of your wordpress installation.
 
 The configuration for munin-node is by default
 at: /etc/munin/plugin-conf.d/munin-node

 Example configuration:
 [wordpress]
 env.NAME Blog of Chuck Norris
 env.CONF /var/www/wordpress/wp-config.php


 ---- More details ----
 @Author...: Patrik Kernstock
 @Version..: v1.0
 @Date.....: 24 November 2012
 @Web......: http://pkern.at
 @Support..: support@pkern.at

*/
#%# family=auto
#%# capabilities=autoconf

// Get configuration variables
$name = getenv("NAME");
$conf = getenv("CONF");

if(empty($name) || empty($conf)) {
	echo "Error: One of the two variables are not set. (NAME, CONF)\n";
}

// In which category it should be displayed
$category = "other";

if($argv[1] == "config") {
	echo 'graph_title wordpress statistic of '.$name."\n";
	echo 'graph_order users posts comments pingbacks'."\n";
	echo 'graph_vlabel Wordpress'."\n";
	echo 'graph_info some wordpress statistics of '.$name."\n";
	echo 'graph_category '.$category."\n";
	echo 'users.label Users'."\n";
	echo 'posts.label Posts'."\n";
	echo 'posts.draw LINE3'."\n";
	echo 'comments.label Comments'."\n";
	echo 'pingbacks.label Pingbacks'."\n";
    exit(0);

}else if($argv[1] == "autoconf") {
	if(file_exists($conf)) {
		echo "yes";
		exit(0);
	 }else{
		echo "no (config does not exist)";
		exit(1);
	}
}

if(!file_exists($conf)) {
	echo "Error: config does not exist!";
	exit(1);
}

// INCLUDE wp-config.php
define("ABSPATH", str_replace("wp-config.php", "", $conf));
require_once($conf);

// INIT VARIABLES
$users     = 0;
$posts     = 0;
$comments  = 0;
$pingbacks = 0;

// GET DATA
mysql_connect(DB_HOST, DB_USER, DB_PASSWORD);
mysql_select_db(DB_NAME);

$users     = mysql_result(mysql_query("SELECT COUNT(*) FROM ".$table_prefix."users;"), 0);
$posts     = mysql_result(mysql_query("SELECT COUNT(*) FROM ".$table_prefix."posts    WHERE post_status='publish' AND post_password='' AND post_type='post';"), 0);
$comments  = mysql_result(mysql_query("SELECT COUNT(*) FROM ".$table_prefix."comments WHERE comment_approved='1' AND comment_type='';"), 0);
$pingbacks = mysql_result(mysql_query("SELECT COUNT(*) FROM ".$table_prefix."comments WHERE comment_approved='1' AND comment_type='pingback';"), 0);

// OUTPUT DATA
echo     "users.value ".$users    ."\n";
echo     "posts.value ".$posts    ."\n";
echo  "comments.value ".$comments ."\n";
echo "pingbacks.value ".$pingbacks."\n";

?>